version: 2
jobs:
#  dependencies:
#    staps:
#      - run: pip install flake8==2.2.3
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install flake8
          command: pip install flake8==2.2.3
      - run:
          name: instasll requirements
          command: pip install -r requirements.txt
      - run:
          name: install ansible
          command: pip install ansible==1.9.2

  production:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Run s3_backup.yml for prodaction
          command: ansible-playbook -u ubuntu -i "54.171.112.103," ansible/tools/s3_backup.yml --extra-vars "target=54.171.112.103" --extra-vars "user=ubuntu"
      - run:
          name: Run prodation.yml for prodaction
          command: ansible-playbook -u ubuntu -i "54.171.112.103," ansible/production.yml --extra-vars "version=master"
      - run:
          name: Run clear_cache.yml for prodaction
          command: ansible-playbook -u ubuntu -i "54.171.112.103," ansible/clear_cache.yml --extra-vars "target=54.171.112.103"

  staging:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Run prodation.yml for stagings
          command: ansible-playbook -u ubuntu -i "54.171.221.157," ansible/production.yml --extra-vars "version=staging_new"
      - run:
          name: Run clear_cache.yml for stagings
          command: ansible-playbook -u ubuntu -i "54.171.221.157," ansible/clear_cache.yml --extra-vars "target=54.171.221.157"

workflows:
  version: 2
  production_and_staging:
    jobs:
      - build
      - production:
          requires:
            - build
          filters:
            branches:
              only: master
      - staging:
          requires:
            - build
          filters:
            branches:
              only: development
