version: 2
jobs:
#  dependencies:
#    staps:
#      - run: pip install flake8==2.2.3
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
#      - run:
#          name: install flake8
#          command: pip install flake8==2.2.3
#      - run:
#          name: instasll requirements
#          command: pip install -r requirements.txt
#      - run:
#          name: install ansible
#          command: pip install ansible==1.9.2
      - run:
          name: Print the Current Time build tests
          command: date
          timeout: 1800


  production:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo tasks for master.
      - run:
          name: Print the Current Time
          command: date

  staging:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo tasks for development.
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  production_and_staging:
    jobs:
      - build
      - production:
          requires:
            - build
          filters:
            branches:
              only: master
      - staging:
          requires:
            - build
          filters:
            branches:
              only: development
