version: 2
jobs:
#  dependencies:
#    staps:
#      - run: pip install flake8==2.2.3


  production:
    docker:
      - image: debian:stretch
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo tasks for master.
      - run:
          name: Print the Current Time
          command: date

  staging:
    docker:
      - image: debian:stretch
    branches:
      only:
        - development
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo tasks for development.
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  production_and_staging:
    jobs:
      - production
      - staging